// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Ris2022.Data;

#nullable disable

namespace Ris2022.Data.Migrations
{
    [DbContext(typeof(RisDBContext))]
    partial class RisDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4a208d09-5385-4890-aba1-9a74fb1e3067",
                            ConcurrencyStamp = "d3614cb7-3cc3-4b59-94cf-59567bc949b1",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "de9ded45-c35f-457a-9ff1-2693c3b56ac0",
                            ConcurrencyStamp = "04a47c88-cc78-4478-8173-5d3268a75f50",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Ris2022.Data.Models.Acceptancetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Acceptancetypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Cost")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Martialstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Martialstatuses");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Modality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aetitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int?>("Departmentid")
                        .IsRequired()
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int?>("Modalitytypeid")
                        .IsRequired()
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int?>("Port")
                        .IsRequired()
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Departmentid");

                    b.HasIndex("Modalitytypeid");

                    b.ToTable("Modalities");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Modalitytype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Modalitytypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Accessionnumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Autoexpiredate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("Clinicid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Departmentid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Doctorid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Documentid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Insertdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("InsertuserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Modalityid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Modalitytypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Ordertypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Patientid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Payreasonid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Paytypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Proceduretypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Reasonid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RisAppDoctorId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("Statusid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Studyid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Updatedate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdateuserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Clinicid");

                    b.HasIndex("Departmentid");

                    b.HasIndex("Modalityid");

                    b.HasIndex("Modalitytypeid");

                    b.HasIndex("Ordertypeid");

                    b.HasIndex("Patientid");

                    b.HasIndex("Paytypeid");

                    b.HasIndex("Proceduretypeid");

                    b.HasIndex("Reasonid");

                    b.HasIndex("RisAppDoctorId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Ordertype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Ordetypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Acceptancetypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Birthplace")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Currentaddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int?>("Gendre")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Givenid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("InsertUserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Insertdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Landphone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int?>("Martialstatusid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Middlename")
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Mobilephone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Mothername")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NationalIdNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Nationalityid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nearestperson")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nearestpersonphone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Notes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Reasonid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Residentaddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Translatedfathername")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Translatedfname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Translatedlname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Translatedmothername")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Updatedate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdateuserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Workaddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Workphone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Worktypeid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Acceptancetypeid");

                    b.HasIndex("Martialstatusid");

                    b.HasIndex("Nationalityid");

                    b.HasIndex("Reasonid");

                    b.HasIndex("Worktypeid");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Paytype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Paytypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Proceduretype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int>("Parentnum")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Proceduretypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("Alergy")
                        .HasColumnType("RAW(2000)");

                    b.Property<int?>("Approved")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Approveddoctorid")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Audiopath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Imagedate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("Meidcalhistory")
                        .HasColumnType("RAW(2000)");

                    b.Property<byte[]>("Notes")
                        .HasColumnType("RAW(2000)");

                    b.Property<int>("Orderid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Parentreport")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Patientid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Physicianid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Raddoctorid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Referingdoctorid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<byte[]>("Reportbody")
                        .HasColumnType("RAW(2000)");

                    b.Property<DateTime>("Reportdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Seriesnumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<byte[]>("Title")
                        .HasColumnType("RAW(2000)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Ris2022.Data.Models.RisAppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ClinicId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Departmentid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Firstname")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<bool?>("Isdoctor")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("Languageid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Lastname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Departmentid");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AppUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3f918696-c57b-4b62-99ac-b15d56dd293d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f86edf09-60f6-4c33-a0c1-1c3de076c049",
                            Email = "RISAdmin@yy.com",
                            EmailConfirmed = true,
                            Firstname = "RIS",
                            Isdoctor = true,
                            Languageid = 1,
                            Lastname = "Admin",
                            LockoutEnabled = false,
                            PasswordHash = "P@ssw0rd123",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0831dc2d-9908-4015-adcf-053246f29b3f",
                            TwoFactorEnabled = false,
                            UserName = "RISAdmin"
                        });
                });

            modelBuilder.Entity("Ris2022.Data.Models.Worktype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Nameen")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Worktypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ris2022.Data.Models.RisAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ris2022.Data.Models.RisAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ris2022.Data.Models.RisAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ris2022.Data.Models.RisAppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ris2022.Data.Models.Modality", b =>
                {
                    b.HasOne("Ris2022.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Departmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ris2022.Data.Models.Modalitytype", "Modalitytype")
                        .WithMany()
                        .HasForeignKey("Modalitytypeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Modalitytype");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Order", b =>
                {
                    b.HasOne("Ris2022.Data.Models.Clinic", "clinic")
                        .WithMany("Orders")
                        .HasForeignKey("Clinicid");

                    b.HasOne("Ris2022.Data.Models.Department", "dept")
                        .WithMany("Orders")
                        .HasForeignKey("Departmentid");

                    b.HasOne("Ris2022.Data.Models.Modality", "modality")
                        .WithMany("Orders")
                        .HasForeignKey("Modalityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ris2022.Data.Models.Modalitytype", "modalitytype")
                        .WithMany("Orders")
                        .HasForeignKey("Modalitytypeid");

                    b.HasOne("Ris2022.Data.Models.Ordertype", "Ordertype")
                        .WithMany("Orders")
                        .HasForeignKey("Ordertypeid");

                    b.HasOne("Ris2022.Data.Models.Patient", "patient")
                        .WithMany("patientOrders")
                        .HasForeignKey("Patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ris2022.Data.Models.Paytype", "paytype")
                        .WithMany("Orders")
                        .HasForeignKey("Paytypeid");

                    b.HasOne("Ris2022.Data.Models.Proceduretype", "proceduretype")
                        .WithMany("Orders")
                        .HasForeignKey("Proceduretypeid");

                    b.HasOne("Ris2022.Data.Models.Reason", "reason")
                        .WithMany("Orders")
                        .HasForeignKey("Reasonid");

                    b.HasOne("Ris2022.Data.Models.RisAppUser", "RisAppDoctor")
                        .WithMany("Orders")
                        .HasForeignKey("RisAppDoctorId");

                    b.Navigation("Ordertype");

                    b.Navigation("RisAppDoctor");

                    b.Navigation("clinic");

                    b.Navigation("dept");

                    b.Navigation("modality");

                    b.Navigation("modalitytype");

                    b.Navigation("patient");

                    b.Navigation("paytype");

                    b.Navigation("proceduretype");

                    b.Navigation("reason");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Patient", b =>
                {
                    b.HasOne("Ris2022.Data.Models.Acceptancetype", "Acceptancetype")
                        .WithMany("patients")
                        .HasForeignKey("Acceptancetypeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ris2022.Data.Models.Martialstatus", "Martialstatus")
                        .WithMany("patients")
                        .HasForeignKey("Martialstatusid");

                    b.HasOne("Ris2022.Data.Models.Nationality", "Nationality")
                        .WithMany("patients")
                        .HasForeignKey("Nationalityid");

                    b.HasOne("Ris2022.Data.Models.Reason", "Reason")
                        .WithMany("Patients")
                        .HasForeignKey("Reasonid");

                    b.HasOne("Ris2022.Data.Models.Worktype", "Worktype")
                        .WithMany("patients")
                        .HasForeignKey("Worktypeid");

                    b.Navigation("Acceptancetype");

                    b.Navigation("Martialstatus");

                    b.Navigation("Nationality");

                    b.Navigation("Reason");

                    b.Navigation("Worktype");
                });

            modelBuilder.Entity("Ris2022.Data.Models.RisAppUser", b =>
                {
                    b.HasOne("Ris2022.Data.Models.Clinic", null)
                        .WithMany("Employees")
                        .HasForeignKey("ClinicId");

                    b.HasOne("Ris2022.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Departmentid");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Acceptancetype", b =>
                {
                    b.Navigation("patients");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Clinic", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Martialstatus", b =>
                {
                    b.Navigation("patients");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Modality", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Modalitytype", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Nationality", b =>
                {
                    b.Navigation("patients");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Ordertype", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Patient", b =>
                {
                    b.Navigation("patientOrders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Paytype", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Proceduretype", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Reason", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Ris2022.Data.Models.RisAppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Worktype", b =>
                {
                    b.Navigation("patients");
                });
#pragma warning restore 612, 618
        }
    }
}
