//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ris2022.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ris2022.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Type.
        /// </summary>
        public static string Acceptancetype {
            get {
                return ResourceManager.GetString("Acceptancetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Modality.
        /// </summary>
        public static string AddModality {
            get {
                return ResourceManager.GetString("AddModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Radigraph.
        /// </summary>
        public static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Patient.
        /// </summary>
        public static string AddPatient {
            get {
                return ResourceManager.GetString("AddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Schudled Radioghraphy.
        /// </summary>
        public static string AddSchudledOrder {
            get {
                return ResourceManager.GetString("AddSchudledOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminstration.
        /// </summary>
        public static string Adminstration {
            get {
                return ResourceManager.GetString("Adminstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE Title.
        /// </summary>
        public static string AETitle {
            get {
                return ResourceManager.GetString("AETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string AlignDir {
            get {
                return ResourceManager.GetString("AlignDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        public static string Birthplace {
            get {
                return ResourceManager.GetString("Birthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        public static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address.
        /// </summary>
        public static string Currentaddress {
            get {
                return ResourceManager.GetString("Currentaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document id.
        /// </summary>
        public static string Documentid {
            get {
                return ResourceManager.GetString("Documentid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patient.
        /// </summary>
        public static string EditPatient {
            get {
                return ResourceManager.GetString("EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameen.
        /// </summary>
        public static string ENARName {
            get {
                return ResourceManager.GetString("ENARName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string failedMes {
            get {
                return ResourceManager.GetString("failedMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string FathName {
            get {
                return ResourceManager.GetString("FathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insersion Date.
        /// </summary>
        public static string Insertdate {
            get {
                return ResourceManager.GetString("Insertdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted By.
        /// </summary>
        public static string InsertUserName {
            get {
                return ResourceManager.GetString("InsertUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Doctor?.
        /// </summary>
        public static string IsDoctor {
            get {
                return ResourceManager.GetString("IsDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Landphone {
            get {
                return ResourceManager.GetString("Landphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Status.
        /// </summary>
        public static string Martialstatus {
            get {
                return ResourceManager.GetString("Martialstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobilephone {
            get {
                return ResourceManager.GetString("Mobilephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalities.
        /// </summary>
        public static string Modalities {
            get {
                return ResourceManager.GetString("Modalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalities Types.
        /// </summary>
        public static string Modalitiestypes {
            get {
                return ResourceManager.GetString("Modalitiestypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality.
        /// </summary>
        public static string Modality {
            get {
                return ResourceManager.GetString("Modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality Name.
        /// </summary>
        public static string ModalityName {
            get {
                return ResourceManager.GetString("ModalityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality Type.
        /// </summary>
        public static string Modalitytype {
            get {
                return ResourceManager.GetString("Modalitytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArabicTerm.
        /// </summary>
        public static string Namear {
            get {
                return ResourceManager.GetString("Namear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Term.
        /// </summary>
        public static string Nameen {
            get {
                return ResourceManager.GetString("Nameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National id Number.
        /// </summary>
        public static string NationalidNumber {
            get {
                return ResourceManager.GetString("NationalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalities.
        /// </summary>
        public static string Nationalities {
            get {
                return ResourceManager.GetString("Nationalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Person.
        /// </summary>
        public static string Nearestperson {
            get {
                return ResourceManager.GetString("Nearestperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Person Phone.
        /// </summary>
        public static string Nearestpersonphone {
            get {
                return ResourceManager.GetString("Nearestpersonphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIS News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        public static string OneClinic {
            get {
                return ResourceManager.GetString("OneClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDepartment.
        /// </summary>
        public static string OneDepartment {
            get {
                return ResourceManager.GetString("OneDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string OnePatient {
            get {
                return ResourceManager.GetString("OnePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiographs Orders.
        /// </summary>
        public static string OrderIndex {
            get {
                return ResourceManager.GetString("OrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string Ordertype {
            get {
                return ResourceManager.GetString("Ordertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Information.
        /// </summary>
        public static string Otherinfo {
            get {
                return ResourceManager.GetString("Otherinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Id.
        /// </summary>
        public static string PatId {
            get {
                return ResourceManager.GetString("PatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientName.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Reason.
        /// </summary>
        public static string Payreasonid {
            get {
                return ResourceManager.GetString("Payreasonid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Type.
        /// </summary>
        public static string Paytype {
            get {
                return ResourceManager.GetString("Paytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Type.
        /// </summary>
        public static string Proceduretype {
            get {
                return ResourceManager.GetString("Proceduretype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuesMark {
            get {
                return ResourceManager.GetString("QuesMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons.
        /// </summary>
        public static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident Address.
        /// </summary>
        public static string Residentaddress {
            get {
                return ResourceManager.GetString("Residentaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiology Information System.
        /// </summary>
        public static string RIS {
            get {
                return ResourceManager.GetString("RIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schudled Radioghraphy .
        /// </summary>
        public static string SchudledOrder {
            get {
                return ResourceManager.GetString("SchudledOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string successMes {
            get {
                return ResourceManager.GetString("successMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SurName {
            get {
                return ResourceManager.GetString("SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Updatedate {
            get {
                return ResourceManager.GetString("Updatedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string UpdateuserName {
            get {
                return ResourceManager.GetString("UpdateuserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Address.
        /// </summary>
        public static string Workaddress {
            get {
                return ResourceManager.GetString("Workaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone.
        /// </summary>
        public static string Workphone {
            get {
                return ResourceManager.GetString("Workphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type.
        /// </summary>
        public static string Worktype {
            get {
                return ResourceManager.GetString("Worktype", resourceCulture);
            }
        }
    }
}
